name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'  # パブリッシュしない設定

version: 1.0.0+1

environment:
  sdk: "^3.5.0"  # Dart SDKバージョン制約

dependencies:
  flutter:
    sdk: flutter  # Flutter SDK
  cupertino_icons: ^1.0.8  # iOSスタイルのアイコン
  audioplayers: ^5.2.1  # 音楽再生用パッケージ
  video_player: ^2.7.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.0.11
  image_picker: ^1.0.7
  just_audio: ^0.9.36
  file_picker: ^6.1.1 # ファイル選択用
 

dev_dependencies:
  flutter_test:
    sdk: flutter  # FlutterテストSDK
  flutter_lints: ^4.0.0  # コードのリントチェック

flutter:
  uses-material-design: true  # マテリアルデザインを使用
  assets:
    - assets/images/takada.jpg  # 画像ファイル
    - assets/audio/takada_kenshi_zanarkand.mp3  # 音声ファイル（引用符で囲んでいる）
    - assets/video/kenshi.mp4
    - assets/images/agehachouu.png
    - assets/video/takadacho.mp4